import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';

const validationRules = [
    { column: 1, field: "No", rule: "Se debe escribir el consecutivo comenzando por el No. 1." },
    { column: 2, field: "Tipo de documento de identidad", rule: "Opciones: CC, MS, TI, PA, CD, AS, CE, PE. No se permite RC." },
    { column: 3, field: "No. De Identificación", rule: "Número de identificación del afiliado." },
    { column: 4, field: "Apellido_1", rule: "Primer apellido, sin símbolos ni tildes." },
    { column: 5, field: "Apellido_2", rule: "Segundo apellido o 'NOAP' si no tiene." },
    { column: 6, field: "Nombre_1", rule: "Primer nombre, sin símbolos ni tildes." },
    { column: 7, field: "Nombre_2", rule: "Segundo nombre o 'NONE' si no tiene." },
    { column: 8, field: "Fecha de Nacimiento", rule: "Formato: AAAA/MM/DD." },
    { column: 9, field: "Edad (años)", rule: "Calculado automáticamente. No modificar." },
    { column: 10, field: "Sexo", rule: "Solo se permite 'Femenino'." },
    { column: 11, field: "Regimen Afiliacion", rule: "Opciones: Subsidiado (S) o Contributivo (C)." },
    { column: 12, field: "Pertenencia Etnica", rule: "Opciones: Indígena, Mestizo, Ningunas de las Anteriores, etc." },
    { column: 13, field: "Grupo Poblacional", rule: "Debe ser 'Mujer Embarazada'." },
    { column: 14, field: "Departamento Residencia", rule: "Nombre del departamento de la IPS." },
    { column: 15, field: "Municipio de Residencia", rule: "Nombre del municipio de la IPS. Opciones: CODAZZI, BECERRIL, VALLEDUPAR, LA PAZ, CHIMICHAGUA, SANTA MARTA, ARACATACA, FUNDACION, CIENAGA, PUEBLO BELLO, SABANAS DE SAN ANGEL, DIBULLA, MAICAO, MANAURE, RIOHACHA, HATONUEVO, SAN JUAN DEL CESAR, BARRANCAS, FONSECA, ALBANIA, DISTRACCION, URIBIA." },
    { column: 16, field: "Zona", rule: "Opciones: Rural, Urbana." },
    { column: 17, field: "Etnia", rule: "Opciones: Wayuu, Arhuaco, etc. Debe ser consistente con 'Pertenencia Étnica'." },
    { column: 18, field: "Asentamiento/Rancheria/Comunidad", rule: "Si es zona rural, ingresar nombre de la comunidad." },
    { column: 19, field: "Teléfono usuaria", rule: "Ingresar obligatoriamente un número de teléfono." },
    { column: 20, field: "Direccion", rule: "Si es zona urbana, ingresar dirección." },
    { column: 21, field: "Nivel Educativo", rule: "Opciones: Analfabeta, Sabe Leer o Escribir, Primaria Completa, etc." },
    { column: 22, field: "Discapacidad", rule: "Opciones: Discapacidad fisica, Discapacidad Psiquica, Discapacidad mental, Ninguna, Sin dato." },
    { column: 23, field: "Mujer cabeza de Hogar", rule: "Opciones: Si, No." },
    { column: 24, field: "Ocupación", rule: "Se debe escribir la Ocupación de la Gestante." },
    { column: 25, field: "Estado Civil", rule: "Opciones: Soltera, Casada, Divorciada, Viuda, Unión Libre." },
    { column: 26, field: "Control Tradicional", rule: "Opciones: Sabedor Ancestral, Partera (o), Sobandera (o)." },
    { column: 27, field: "Gestante Renuente", rule: "Opciones: Si, No." },
    { column: 28, field: "Inasistente", rule: "Opciones: Si, No." },
    { column: 29, field: "Nombre de la IPS Primaria", rule: "Se debe ingresar el Nombre de la IPS/ESE completo sin abreviaturas." },
    { column: 30, field: "Fecha de diagnostico del embarazo", rule: "Formato AAAA/MM/DD. No puede ser anterior a la FUM." },
    { column: 31, field: "Fecha de Ingreso al Control Prenatal", rule: "Formato AAAA/MM/DD. No puede ser anterior a la fecha de diagnóstico." },
    { column: 32, field: "FUM", rule: "Fecha de la última Mestruación. Formato: AAAA/MM/DD." },
    { column: 33, field: "FPP", rule: "Calculado automáticamente. No modificar." },
    { column: 34, field: "Dias para el parto", rule: "Calculado automáticamente. No modificar." },
    { column: 35, field: "Alarma", rule: "Calculado automáticamente. No modificar." },
    { column: 36, field: "Edad Gest Inicio Control", rule: "Calculado automáticamente. No debe ser mayor a 41 ni menor a 3 sin justificación." },
    { column: 37, field: "Trimestre inicio control", rule: "Calculado automáticamente. No modificar." },
    { column: 38, field: "Fórmula obstétrica - G", rule: "Número de embarazos incluyendo el actual." },
    { column: 39, field: "Fórmula obstétrica - P", rule: "Número de partos Vaginales." },
    { column: 40, field: "Fórmula obstétrica - C", rule: "Número de cesareas." },
    { column: 41, field: "Fórmula obstétrica - A", rule: "Número de Abortos." },
    { column: 42, field: "Fórmula obstétrica - M", rule: "Número de Mortinatos." },
    { column: 43, field: "Fórmula obstétrica - V", rule: "Cantidad de hijos vivos." },
    { column: 44, field: "Antecedentes - Hipertension arterial", rule: "Opciones: Si, No." },
    { column: 45, field: "Antecedentes - Diabetes", rule: "Opciones: Si, No." },
    { column: 46, field: "Antecedentes - VIH", rule: "Opciones: Si, No." },
    { column: 47, field: "Antecedentes - Sifilis", rule: "Opciones: Si, No." },
    { column: 48, field: "Antecedentes - Tuberculosis", rule: "Opciones: Si, No." },
    { column: 49, field: "Antecedentes - Otras condiciones medicas graves", rule: "Opciones: Si, No." },
    { column: 50, field: "Descripción otra condición médica", rule: "Si la respuesta anterior es SI, describa." },
    { column: 51, field: "Antecedentes de eventos obstétricos desfavorables", rule: "Opciones: Prematurez, Malformados, Placenta previa, etc. 'Ninguno' si no aplica." },
    { column: 52, field: "Periodo Intergenésico", rule: "Opciones: Ninguno, <12 meses, 12 a 24 meses, etc." },
    { column: 53, field: "Peso Inicial (kg)", rule: "Peso inicial en kg, con coma para decimales." },
    { column: 54, field: "Talla (metros)", rule: "Talla en metros, con coma para decimales." },
    { column: 55, field: "Indice de Masa Corporal (IMC)", rule: "Calculado automáticamente. No modificar." },
    { column: 56, field: "Clasificación del IMC", rule: "Calculado automáticamente. No modificar." },
    { column: 57, field: "Riesgo psicosocial - Apoyo familiar", rule: "Opciones: Si, No, Sin Datos." },
    { column: 58, field: "Riesgo psicosocial - Embarazo deseado", rule: "Opciones: Si, No, Sin Datos." },
    { column: 59, field: "Riesgo psicosocial - Hábitos de riesgo", rule: "Opciones: Ninguno, Fuma, Toma Alcohol, etc." },
    { column: 60, field: "Riesgo psicosocial - Victima de violencia", rule: "Opciones: Si, No, Sin Datos." },
    { column: 61, field: "Riesgo psicosocial - Victima de abuso sexual", rule: "Opciones: Si, No, Sin Datos." },
    { column: 62, field: "Se Identifican Causales Para IVE?", rule: "Opciones: Si, No." },
    { column: 63, field: "Clasificación del riesgo", rule: "Opciones: Alto riesgo obstétrico, Bajo riesgo obstétrico. No puede estar vacío." },
    { column: 64, field: "Causas de Alto Riesgo", rule: "Seleccionar de la lista si el riesgo es alto. No puede estar vacío si es ARO." },
    { column: 65, field: "Puntaje escala de Herrera y Hurtado", rule: "Especificar el puntaje numérico. 'Sin datos' si no aplica." },
    { column: 66, field: "Remitida a especialista?", rule: "Opciones: Si, No." },
    { column: 67, field: "Descripción de especialista", rule: "Especialidad a la que fue remitida (ginecología, perinatología, etc.)." },
    { column: 68, field: "Asesoria Prueba VIH", rule: "Ingresar fecha en formato AAAA/MM/DD." },
    { column: 69, field: "Trimestre Asesoria VIH", rule: "Calculado automáticamente." },
    { column: 70, field: "Fecha Toma Prueba VIH Primer Tamizaje", rule: "Formato AAAA/MM/DD." },
    { column: 71, field: "Resultado Primer Tamizaje prueba de VIH", rule: "Opciones: Positivo, Negativo." },
    { column: 72, field: "Trimestre Toma Prueba VIH Primer Tamizaje", rule: "Calculado automáticamente." },
    { column: 73, field: "Fecha Toma Prueba VIH Segundo Tamizaje", rule: "Formato AAAA/MM/DD. Debe ser > 90 días después del primer tamizaje." },
    { column: 74, field: "Resultado Segundo Tamizaje Prueba de VIH", rule: "Opciones: Positivo, Negativo." },
    { column: 75, field: "Trimestre Toma Prueba VIH Segundo Tamizaje", rule: "Calculado automáticamente." },
    { column: 76, field: "Fecha Toma Prueba VIH Tercer Tamizaje", rule: "Formato AAAA/MM/DD. Debe ser > 180 días del primero y > 90 días del segundo." },
    { column: 77, field: "Resultado Tercer Tamizaje Prueba de VIH", rule: "Opciones: Positivo, Negativo." },
    { column: 78, field: "Trimestre Toma Prueba VIH Tercer Tamizaje", rule: "Calculado automáticamente." },
    { column: 79, field: "Fecha Primera Prueba Treponemica Rapida Sifilis", rule: "Formato AAAA/MM/DD." },
    { column: 80, field: "Resultado Primera Prueba Treponemica Rápida Sífilis", rule: "Opciones: Positivo, Negativo." },
    { column: 81, field: "Trimestre Primera Prueba Treponemica Rapida Sifilis", rule: "Calculado automáticamente." },
    { column: 82, field: "Fecha Segunda Prueba Treponemica Rapida Sifilis", rule: "Formato AAAA/MM/DD." },
    { column: 83, field: "Resultado Segunda Prueba Treponemica Rápida Sífilis", rule: "Opciones: Positivo, Negativo." },
    { column: 84, field: "Trimestre Segunda Prueba Treponemica Rapida Sifilis", rule: "Calculado automáticamente." },
    { column: 85, field: "Fecha Tercera Prueba Treponemica Rapida Sifilis", rule: "Formato AAAA/MM/DD." },
    { column: 86, field: "Resultado Tercera Prueba Treponemica Rápida Sífilis", rule: "Opciones: Positivo, Negativo." },
    { column: 87, field: "Trimestre Tercera Prueba Treponemica Rapida Sifilis", rule: "Calculado automáticamente." },
    { column: 88, field: "Fecha toma Segunda Prueba VIH", rule: "Formato AAAA/MM/DD." },
    { column: 89, field: "Resultado Toma Segunda Prueba VIH", rule: "Opciones: Positivo, Negativo." },
    { column: 90, field: "Trimestre Toma segunda Prueba VIH", rule: "Calculado automáticamente." },
    { column: 91, field: "Fecha prueba confirmatoria Según Algoritmo", rule: "Formato AAAA/MM/DD." },
    { column: 92, field: "Trimestre Prueba confirmatoria Según Algoritmo", rule: "Calculado automáticamente." },
    { column: 93, field: "Fecha prueba No Treponemica para sifilis", rule: "Formato AAAA/MM/DD." },
    { column: 94, field: "Resultado Prueba No Treponemica para sifilis", rule: "Opciones: Positivo, Negativo." },
    { column: 95, field: "Trimestre Prueba No Treponemica para sifilis", rule: "Calculado automáticamente." },
    { column: 96, field: "Fecha de Toma de Urocultivo", rule: "Formato AAAA/MM/DD." },
    { column: 97, field: "Resultado Urocultivo", rule: "Si se ingresa fecha, se debe ingresar resultado." },
    { column: 98, field: "Fecha Toma Glicemia", rule: "Formato AAAA/MM/DD." },
    { column: 99, field: "Resultado Glicemia", rule: "Resultado numérico." },
    { column: 100, field: "Fecha Prueba de Tolerancia Oral Glucosa", rule: "Formato AAAA/MM/DD." },
    { column: 101, field: "Resultado Prueba de Tolerancia Oral Glucosa", rule: "Resultado numérico." },
    { column: 102, field: "Fecha Realizacion Hemoglobina", rule: "Formato AAAA/MM/DD." },
    { column: 103, field: "Resultado Hemoglobina", rule: "Resultado numérico." },
    { column: 104, field: "Resultado Realizacion Hemoclasificación (Factor RH)", rule: "Opciones: O+, O-, A+, A-, AB+, AB-, B+, B-." },
    { column: 105, field: "Fecha de Antigeno Superficie Hepatitis B", rule: "Formato AAAA/MM/DD." },
    { column: 106, field: "Resultado Antigeno Superficie Hepatitis B", rule: "Opciones: Negativo, Positivo." },
    { column: 107, field: "Fecha Tamizaje Toxoplasma", rule: "Formato AAAA/MM/DD." },
    { column: 108, field: "Resultado Toxoplasma", rule: "Opciones: Negativo, Positivo." },
    { column: 109, field: "Fecha de la prueba de Rubeola", rule: "Formato AAAA/MM/DD." },
    { column: 110, field: "Resultado Rubeola", rule: "Opciones: Negativo, Positivo." },
    { column: 111, field: "Fecha Citologia Cervicouterina", rule: "Formato AAAA/MM/DD." },
    { column: 112, field: "Resultado Tamizaje de cuello uterino", rule: "Opciones: Normal, Alterado." },
    { column: 113, field: "Fecha Frotis Vaginal", rule: "Formato AAAA/MM/DD." },
    { column: 114, field: "Resultado Frotis Vaginal", rule: "Opciones: Normal, Alterado." },
    { column: 115, field: "Fecha Prueba de Tamizaje para Estreptococo Grupo B", rule: "Formato AAAA/MM/DD." },
    { column: 116, field: "Resultado Prueba de Tamizaje para Estreptococo Grupo B", rule: "Opciones: Negativo, Positivo." },
    { column: 117, field: "Fecha Toma de Gota Gruesa (Malaria)", rule: "Formato AAAA/MM/DD." },
    { column: 118, field: "Resultado Gota gruesa (Malaria)", rule: "Opciones: Negativo, Positivo." },
    { column: 119, field: "Fecha de Realización Tamizaje Chagas", rule: "Formato AAAA/MM/DD." },
    { column: 120, field: "Resultado Chagas", rule: "Opciones: Negativo, Positivo." },
    { column: 121, field: "FECHA DE APLICACIÓN INFLUENZA (Desde Semana 14)", rule: "Formato AAAA/MM/DD." },
    { column: 122, field: "FECHA DE APLICACIÓN TOXOIDE Según Antecedente Vacunal", rule: "Formato AAAA/MM/DD." },
    { column: 123, field: "FECHA DE APLICACIÓN DPT ACELULAR (Semana 26)", rule: "Formato AAAA/MM/DD." },
    { column: 124, field: "Fecha Consulta Odontologica", rule: "Formato AAAA/MM/DD." },
    { column: 125, field: "Ecografia con translucencia nucal (10.6-13.6)", rule: "Formato AAAA/MM/DD." },
    { column: 126, field: "Ecografia para detección de anomalias (18-23)", rule: "Formato AAAA/MM/DD." },
    { column: 127, field: "Otras ecografías?", rule: "Formato AAAA/MM/DD." },
    { column: 128, field: "Fecha suministro Acido Folico", rule: "Formato AAAA/MM/DD." },
    { column: 129, field: "Fecha suministro Calcio (Semana 14)", rule: "Formato AAAA/MM/DD." },
    { column: 130, field: "Fecha suministro Hierro", rule: "Formato AAAA/MM/DD." },
    { column: 131, field: "Suministro de ASA - fecha", rule: "Formato AAAA/MM/DD." },
    { column: 132, field: "Fecha Desparasitación", rule: "Formato AAAA/MM/DD." },
    { column: 133, field: "Información en Salud", rule: "Opciones: Si, No." },
    { column: 134, field: "Fecha 1er Control", rule: "Formato AAAA/MM/DD." },
    { column: 135, field: "Quien Realizó el Control 1", rule: "Opciones: Médico, Aux de Enfermeria, Enfermera (o), etc." },
    { column: 136, field: "Fecha 2do Control", rule: "Formato AAAA/MM/DD." },
    { column: 137, field: "Quien Realizó el Control 2", rule: "Opciones: Médico, Aux de Enfermeria, Enfermera (o), etc." },
    { column: 138, field: "Fecha 3er Control", rule: "Formato AAAA/MM/DD." },
    { column: 139, field: "Quien Realizó el Control 3", rule: "Opciones: Médico, Aux de Enfermeria, Enfermera (o), etc." },
    { column: 140, field: "Fecha 4to Control", rule: "Formato AAAA/MM/DD." },
    { column: 141, field: "Quien Realizó el Control 4", rule: "Opciones: Médico, Aux de Enfermeria, Enfermera (o), etc." },
    { column: 142, field: "Fecha 5to Control", rule: "Formato AAAA/MM/DD." },
    { column: 143, field: "Quien Realizó el Control 5", rule: "Opciones: Médico, Aux de Enfermeria, Enfermera (o), etc." },
    { column: 144, field: "Fecha 6to Control", rule: "Formato AAAA/MM/DD." },
    { column: 145, field: "Quien Realizó el Control 6", rule: "Opciones: Médico, Aux de Enfermeria, Enfermera (o), etc." },
    { column: 146, field: "Fecha 7mo Control", rule: "Formato AAAA/MM/DD." },
    { column: 147, field: "Quien Realizó el Control 7", rule: "Opciones: Médico, Aux de Enfermeria, Enfermera (o), etc." },
    { column: 148, field: "fecha 8vo Control", rule: "Formato AAAA/MM/DD." },
    { column: 149, field: "Quien Realizó el Control 8", rule: "Opciones: Médico, Aux de Enfermeria, Enfermera (o), etc." },
    { column: 150, field: "Fecha 9no Control", rule: "Formato AAAA/MM/DD." },
    { column: 151, field: "Quien Realizó el Control 9", rule: "Opciones: Médico, Aux de Enfermeria, Enfermera (o), etc." },
    { column: 152, field: "Número Total de Controles Prenatales", rule: "Calculado automáticamente." },
    { column: 153, field: "Ultimo Control Prenatal", rule: "Calculado automáticamente." },
    { column: 154, field: "Edad Gestacional actual", rule: "Calculado automáticamente." },
    { column: 155, field: "Peso Actual", rule: "Peso en kg, con coma para decimales." },
    { column: 156, field: "Talla actual", rule: "Talla en metros, con coma para decimales." },
    { column: 157, field: "IMC", rule: "Calculado automáticamente." },
    { column: 158, field: "Fecha Primera Consulta Ginecología", rule: "Formato AAAA/MM/DD." },
    { column: 159, field: "Fecha Segunda Consulta Ginecología", rule: "Formato AAAA/MM/DD." },
    { column: 160, field: "Fecha Tercera Consulta Ginecología", rule: "Formato AAAA/MM/DD." },
    { column: 161, field: "Fecha Consulta Nutrición", rule: "Formato AAAA/MM/DD." },
    { column: 162, field: "Fecha Consulta Psicología", rule: "Formato AAAA/MM/DD." },
    { column: 163, field: "Fecha de Atención Otro Especialista", rule: "Formato AAAA/MM/DD." },
    { column: 164, field: "Quien Realizó la Consulta", rule: "Nombre de la especialidad." },
    { column: 165, field: "ABORTO - Tipo", rule: "Opciones: IVE, Expontáneo, Provocado, sin datos." },
    { column: 166, field: "ABORTO - Fecha", rule: "Formato AAAA/MM/DD." },
    { column: 167, field: "ABORTO - Semanas de Gestación", rule: "Número de semanas." },
    { column: 168, field: "ABORTO - Complicaciones", rule: "Descripción de complicaciones." },
    { column: 169, field: "PARTO - Fecha de Parto", rule: "Formato AAAA/MM/DD." },
    { column: 170, field: "PARTO - Caracteristicas del parto", rule: "Opciones: Parto Vaginal, Cesarea, Tradicional." },
    { column: 171, field: "PARTO - Parto atendido por", rule: "Opciones: IPS baja complejidad, IPS mediana o alta, Partera, etc." },
    { column: 172, field: "PARTO - No. Semanas de gestación", rule: "Número de semanas." },
    { column: 173, field: "PARTO - Complicaciones durante el parto", rule: "Opciones: Si, No." },
    { column: 174, field: "PARTO - Tipo Complicación", rule: "Opciones: Parto prematuro, RPM, Hemorragia, etc." },
    { column: 175, field: "PARTO - UCI Materna", rule: "Opciones: Si, No." },
    { column: 176, field: "PARTO - Toma de pruebas ITS intraparto", rule: "Opciones: No, Sifilis, VIH, Sífilis y VIH." },
    { column: 177, field: "PARTO - Resultado POSITIVO", rule: "Opciones: Si, No." },
    { column: 178, field: "DEFUNCION - Fecha", rule: "Formato AAAA/MM/DD." },
    { column: 179, field: "DEFUNCION - Causa de la defunción", rule: "Causa básica de la muerte." },
    { column: 180, field: "Multiplicidad del embarazo", rule: "Opciones: Simple, Doble, Triple, Cuadruple o más." },
    { column: 181, field: "Recien Nacido 1 - Registro Civil", rule: "Número del registro civil." },
    { column: 182, field: "Recien Nacido 1 - Nombre", rule: "Nombre completo del recién nacido." },
    { column: 183, field: "Recien Nacido 1 - Sexo", rule: "Opciones: Masculino, Femenino." },
    { column: 184, field: "Recien Nacido 1 - Peso al nacer (grs)", rule: "Peso en gramos." },
    { column: 185, field: "Recien Nacido 1 - Condición", rule: "Opciones: Vivo, Muerto." },
    { column: 186, field: "Recien Nacido 1 - Toma TSH", rule: "Opciones: Si, No." },
    { column: 187, field: "Recien Nacido 1 - Dx. Hipotiroidismo", rule: "Opciones: Si, No." },
    { column: 188, field: "Recien Nacido 1 - TTO Hipotiroidismo", rule: "Opciones: Si, No." },
    { column: 189, field: "Recien Nacido 1 - Tiempo de lectura", rule: "Tiempo de lectura." },
    { column: 190, field: "Recien Nacido 1 - UCI Neonatal", rule: "Opciones: Si, No." },
    { column: 191, field: "Recien Nacido 1 - Vacunación con BCG", rule: "Opciones: Si, No." },
    { column: 192, field: "Recien Nacido 1 - Vacunación Antihepatitis B", rule: "Opciones: Si, No." },
    { column: 193, field: "Recien Nacido 2 - Registro Civil", rule: "Número del registro civil." },
    { column: 194, field: "Recien Nacido 2 - Nombre", rule: "Nombre completo del recién nacido." },
    { column: 195, field: "Recien Nacido 2 - Sexo", rule: "Opciones: Masculino, Femenino." },
    { column: 196, field: "Recien Nacido 2 - Peso al nacer", rule: "Peso en gramos." },
    { column: 197, field: "Recien Nacido 2 - Condición", rule: "Opciones: Vivo, Muerto." },
    { column: 198, field: "Recien Nacido 2 - Toma TSH", rule: "Opciones: Si, No." },
    { column: 199, field: "Recien Nacido 2 - Dx. Hipotiroidismo", rule: "Opciones: Si, No." },
    { column: 200, field: "Recien Nacido 2 - Tiempo de lectura", rule: "Tiempo de lectura." },
    { column: 201, field: "Recien Nacido 2 - TTO Hipotiroidismo", rule: "Opciones: Si, No." },
    { column: 202, field: "Recien Nacido 2 - Vacunación con BCG", rule: "Opciones: Si, No." },
    { column: 203, field: "Recien Nacido 2 - Vacunación Antihepatitis B", rule: "Opciones: Si, No." },
    { column: 204, field: "PLANIFICACION - TIPO", rule: "Opciones: DIU, Inyeccion mensual, Inyeccion trimestral, Pildoras, etc." },
    { column: 205, field: "PLANIFICACION - OBSEVACION", rule: "Observaciones sobre la planificación." },
    { column: 206, field: "PLANIFICACION - FECHA", rule: "Formato AAAA/MM/DD." },
    { column: 207, field: "SEGUIMIENTO ARO", rule: "Diligenciar el seguimiento si se clasifica como ARO." },
    { column: 208, field: "OBSERVACION GENERAL", rule: "Describir la observación general." }
];

export function GestantesValidationRules() {
  return (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead className="w-[80px]">Columna</TableHead>
          <TableHead>Campo</TableHead>
          <TableHead>Regla de Validación Principal</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {validationRules.map((rule) => (
          <TableRow key={rule.column}>
            <TableCell className="font-medium text-center">{rule.column}</TableCell>
            <TableCell>{rule.field}</TableCell>
            <TableCell>{rule.rule}</TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  );
}
