
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';

const validationRules = [
    { column: 1, field: "N°", rule: "Se debe escribir el consecutivo comenzando por el No. 1" },
    { column: 2, field: "PRI NOMBRE", rule: "Ingresar Primer Nombre" },
    { column: 3, field: "SEG NOMBRE", rule: "Ingresar Segundo Nombre" },
    { column: 4, field: "PRI APELLIDO", rule: "Ingresar Primer Apellido" },
    { column: 5, field: "SEG APELLIDO", rule: "Ingresar Segundo Apellido" },
    { column: 6, field: "TI IDENTIFICIÓN", rule: "Opciones: CC, MS, RC, TI, PA, CD, AS, PT" },
    { column: 7, field: "NÚMERO DE IDENTIFICACIÓN", rule: "Ingresar el número de identificación" },
    { column: 8, field: "FECHA DE NACIMIENTO", rule: "Se debe escribir la fecha de nacimiento de la siguiente forma: año/mes/día" },
    { column: 9, field: "60 Y MAS AÑOS ?", rule: "Este campo es calculado automaticamente, no se debe modificar la Fómula" },
    { column: 10, field: "EDAD", rule: "Este campo es calculado automaticamente, no se debe modificar la Fómula" },
    { column: 11, field: "SEXO", rule: "Opciones: Femenino, Masculino" },
    { column: 12, field: "RÉGIMEN DE AFILACIÓN", rule: "Opciones: Subsidiado: S, Contributivo: C" },
    { column: 13, field: "PERTENENCIA ÉTNICA", rule: "Opciones: Indígena, ROM (Gitano), Raizal del Archipielago, Negro (a), Mulato, Afroamericano, Mestizo, Ningunas de las Anteriores" },
    { column: 14, field: "GRUPO POBLACIONAL", rule: "Opciones: Población Infantil a cargo del ICBF, Mujer Cabeza de Hogar, Discapacitados, Otro Grupo Poblacional, Desmovilizados, Adulto Mayor, Victimas del Conflicto Armado" },
    { column: 15, field: "ETNIA", rule: "Opciones: Wayuu, Arhuaco, Wiwa, Yukpa, Kogui, Inga, Kankuamo, Chimila, Zenu, Sin Etnia" },
    { column: 16, field: "DEPARTAMENTO DE RESIDENCIA", rule: "Se debe ingresar el Dpto donde reside al paciente" },
    { column: 17, field: "MUNICPIO DE RESIDENCIA", rule: "Se debe ingresar el Municipio de la Ipsi" },
    { column: 18, field: "NÚMERO DE TELEFONO", rule: "Ingresar número de telefono fijo o celular de contacto" },
    { column: 19, field: "ZONA DE UBICACIÓN DE LA VIVIENDA", rule: "Opciones: Rural, Urbana" },
    { column: 20, field: "DIRECCION", rule: "Si seleccionó zona urbana debe ingresar la direccion" },
    { column: 21, field: "ASENTAMIENTO/RANCHERIA", rule: "Si seleccionó zona rural debe ingresar el nombre del asentamiento, comunidad o Rancheria donde reside el paciente" },
    { column: 22, field: "CODIGO DE LA IPS QUE HACE SEGUIMIENTO", rule: "Se debe ingresar el Código de Habilitación de la IPS que presta los servicios de salud" },
    { column: 23, field: "NOMBRE DE LA IPS QUE HACE SEGUIMIENTO", rule: "Se debe ingresar el Nombre de la IPS" },
    { column: 24, field: "FECHA INSCRIPCION PROGRAMA DE HTA - DM)", rule: "Fecha de Ingreso al programa de la siguiente forma: Año/Mes/ Día" },
    { column: 25, field: "FUMA", rule: "Opciones: Si, No" },
    { column: 26, field: "CONSUMO DE ALCOHOL", rule: "Opciones: Si, No" },
    { column: 27, field: "DX CONFIRMADO HTA", rule: "Opciones: Si, No" },
    { column: 28, field: "FECHA DX", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 29, field: "DX CONFIRMADO DM", rule: "Opciones: Si, No" },
    { column: 30, field: "FECHA DX", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 31, field: "TIPO DE DM", rule: "Opciones: -Tipo 1 Insulinodependiente, -Tipo 2 No Insulinodependiente, -No Aplica" },
    { column: 32, field: "Etiología de la ERC", rule: "Opciones: -HTA o DM, -Autoinmune, -Nefropatía Obstructiva, -Enfermedad Poliquistica, -No tiene ERC, -Otras" },
    { column: 33, field: "TENSIÓN ARTERIAL SISTÓLICA AL INGRESO A BASE", rule: "Ingresar Presión Arterial Sistólica en número sin agregar letras" },
    { column: 34, field: "TENSIÓN ARTERIAL DIASTÓLICA AL INGRESO A BASE", rule: "Ingresar Presión Arterial Diastólica en Número sin agregar letras" },
    { column: 35, field: "CLASIFICACION DE HTA DE INGRESO", rule: "Este campo se calcula automaticamente, no se debe modificar la Fómula" },
    { column: 36, field: "HTA CONTROLADA", rule: "Opciones: Si, No" },
    { column: 37, field: "ÚLTIMO PESO", rule: "Se debe ingresar el peso en cada uno de los controles" },
    { column: 38, field: "TALLA", rule: "Se debe ingresar la talla en metros, separado por coma" },
    { column: 39, field: "IMC", rule: "Este campo se calcula automaticamente, no se debe modificar la Fómula" },
    { column: 40, field: "CLASIFICACION DE IMC", rule: "Este campo se calcula automaticamente, no se debe modificar la Fómula" },
    { column: 41, field: "ÚLTIMA MEDICIÓN DE PERIMETRO ABDOMINAL", rule: "Se debe ingresar la última medición en número" },
    { column: 42, field: "FACTOR DE RIESGO POR PA", rule: "Este campo se calcula automaticamente, no se debe modificar la Fómula" },
    { column: 43, field: "CLASIFICACION DEL RCV ACTUAL AL INGRESO A BASE", rule: "Opciones: -Riesgo Alto, -Riesgo Bajo, -Riesgo Moderado, -No se Clasifico" },
    { column: 44, field: "FECHA DE CLASIFICACIÓN DE RCV AL INGRESO A BASE", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 45, field: "CLASIFICACION DEL RCV ACTUAL", rule: "Este campo se calcula automaticamente, no se debe modificar la Fómula" },
    { column: 46, field: "FECHA DE CLASIFICACIÓN DE RCV", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 47, field: "HEMOGRAMA", rule: "Se debe ingresar el resultado en número sin adicionar letras" },
    { column: 48, field: "FECHA DEL HEMOGRAMA", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 49, field: "GLICEMIA BASAL", rule: "Se debe ingresar el resultado en número sin adicionar letras" },
    { column: 50, field: "FECHA DE GLICEMIA BASAL", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 51, field: "PARCIAL DE ORINA", rule: "Opciones: -Normal, -Proteinura, -Hematuria, -Otra" },
    { column: 52, field: "FECHA PARCIAL DE ORINA", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 53, field: "CREATININA SANGRE (mg/dl)", rule: "Se debe ingresar el resultado en número sin adicionar letras" },
    { column: 54, field: "FECHA CREATININA SANGRE", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 55, field: "COLESTEROL TOTAL", rule: "Se debe ingresar el resultado en número sin adicionar letras" },
    { column: 56, field: "HDL", rule: "Se debe ingresar el resultado en número sin adicionar letras" },
    { column: 57, field: "LDL", rule: "Se debe ingresar el resultado en número sin adicionar letras" },
    { column: 58, field: "TRIGLICERIDOS", rule: "Se debe ingresar el resultado en número sin adicionar letras" },
    { column: 59, field: "FECHA PERFIL LIPIDICO", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 60, field: "FECHA DE SOLICITUD DE HEMOGLOBINA GLICOSILADA", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 61, field: "REPORTE DE HEMOGLOBINA GLICOSILADA (SOLO PARA USUARIOS CON DX DE DM)", rule: "Se debe ingresar el resultado en número sin adicionar letras" },
    { column: 62, field: "FECHA DE REPORTE DE HEMOGLOBINA GLICOSILADA", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 63, field: "DM CONTROLADA", rule: "Opciones: Si, No" },
    { column: 64, field: "ALBUMINURIA", rule: "Se debe ingresar el resultado en número sin adicionar letras" },
    { column: 65, field: "FECHA ALBUMINURIA", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 66, field: "REPORTE DE EKG", rule: "Opciones: -Normal, -Enf. Coronaria, -Trans. Ritmo, -Hipertrofia Ventricular, -Hipertrofia Auricular, -Otro" },
    { column: 67, field: "FECHA DE EKG", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 68, field: "ECOCARDIOGRAMA", rule: "Si el resultado es Normal se debe ingresar Si, si presenta anomalia colocar No" },
    { column: 69, field: "FECHA DE REPORTE DEL ECOCARDIOGRAMA", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 70, field: "AJUSTE TFG POR GENERO", rule: "" },
    { column: 71, field: "TFG AJUSTADA POR GENERO fórmula Cockcroft and Gault", rule: "" },
    { column: 72, field: "TFG fórmula Cockcroft and Gault Actual", rule: "" },
    { column: 73, field: "TFG fórmula Cockcroft and Gault Anterior", rule: "" },
    { column: 74, field: "variabilidad", rule: "" },
    { column: 75, field: "fecha creatinnina Actual", rule: "" },
    { column: 76, field: "Creatinina Actual", rule: "" },
    { column: 77, field: "fecha creatinnina Anterior", rule: "" },
    { column: 78, field: "Creatinina Anterior", rule: "" },
    { column: 79, field: "ESTADIO SEGÚN TFG", rule: "" },
    { column: 80, field: "DESCRIPCION DEL DAÑO RENAL", rule: "" },
    { column: 81, field: "ENERO FECHA", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 82, field: "CONTROL REALIZADO POR", rule: "Opciones: -Medico, -Enfermera, -Aux. Enfermeria" },
    { column: 83, field: "FEBRERO FECHA", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 84, field: "CONTROL REALIZADO POR", rule: "Opciones: -Medico, -Enfermera, -Aux. Enfermeria" },
    { column: 85, field: "MARZO FECHA", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 86, field: "CONTROL REALIZADO POR", rule: "Opciones: -Medico, -Enfermera, -Aux. Enfermeria" },
    { column: 87, field: "ABRIL FECHA", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 88, field: "CONTROL REALIZADO POR", rule: "Opciones: -Medico, -Enfermera, -Aux. Enfermeria" },
    { column: 89, field: "MAYO FECHA", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 90, field: "CONTROL REALIZADO POR", rule: "Opciones: -Medico-Enfermera, -Aux. Enfermeria" },
    { column: 91, field: "JUNIO FECHA", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 92, field: "CONTROL REALIZADO POR", rule: "Opciones: -Medico-Enfermera, -Aux. Enfermeria" },
    { column: 93, field: "JULIO FECHA", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 94, field: "CONTROL REALIZADO POR", rule: "Opciones: -Medico, -Enfermera, -Aux. Enfermeria" },
    { column: 95, field: "AGOSTO FECHA", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 96, field: "CONTROL REALIZADO POR", rule: "Opciones: -Medico, -Enfermera, -Aux. Enfermeria" },
    { column: 97, field: "SEPTIEMBRE FECHA", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 98, field: "CONTROL REALIZADO POR", rule: "Opciones: -Medico, -Enfermera, -Aux. Enfermeria" },
    { column: 99, field: "OCTUBRE FECHA", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 100, field: "CONTROL REALIZADO POR", rule: "Opciones: -Medico, -Enfermera, -Aux. Enfermeria" },
    { column: 101, field: "NOVIEMBRE FECHA", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 102, field: "CONTROL REALIZADO POR", rule: "Opciones: -Medico, -Enfermera, -Aux. Enfermeria" },
    { column: 103, field: "DICIEMBRE FECHA", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 104, field: "CONTROL REALIZADO POR", rule: "Opciones: -Medico, -Enfermera, -Aux. Enfermeria" },
    { column: 105, field: "FECHA DE PROXIMO CONTROL", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 106, field: "ÚLTIMA TENSIÓN ARTERIAL SISTÓLICA", rule: "Ingresar Ultima Medición de Presión Arterial Sistólica en número sin agregar letras" },
    { column: 107, field: "ÚLTIMA TENSIÓN ARTERIAL DIASTÓLICA", rule: "Ingresar Ultima Medición de Presión Arterial Diastólica en Número, sin agregar letras" },
    { column: 108, field: "CLASIFICACION DE HTA", rule: "Este campo se calcula automaticamente, no se debe modificar la Fómula" },
    { column: 109, field: "FECHA DE LA ULTIMA TOMA DE PRESION ARTERIAL REPORTADO EN HISTORIA CLÍNICA", rule: "Este campo se calcula automaticamente de acuerdoi a la última fecha de controll ingresada, no se debe modificar la Fómula" },
    { column: 110, field: "HTA CONTROLADA", rule: "Este campo se calcula automaticamente, no se debe modificar la Fómula" },
    { column: 111, field: "Medicamento IECA", rule: "Ingresar el nombre del medicamento instaurado por el medico tratante" },
    { column: 112, field: "Medicamento ARA II", rule: "Ingresar el nombre del medicamento instaurado por el medico tratante" },
    { column: 113, field: "Medicamento Calcioantagonista", rule: "Ingresar el nombre del medicamento instaurado por el medico tratante" },
    { column: 114, field: "Medicamento Betabloqueador", rule: "Ingresar el nombre del medicamento instaurado por el medico tratante" },
    { column: 115, field: "Medicamento Diurético", rule: "Ingresar el nombre del medicamento instaurado por el medico tratante" },
    { column: 116, field: "Medicamento Estatina", rule: "Ingresar el nombre del medicamento instaurado por el medico tratante" },
    { column: 117, field: "Otro Medicamento", rule: "Ingresar el nombre del medicamento instaurado por el medico tratante" },
    { column: 118, field: "ADHERENCIA AL TRATAMIENTO FARMACOLOGICO (TEST DE MORISKY GREEN)", rule: "Opciones: -Si, -No" },
    { column: 119, field: "REMITIDO A", rule: "Ingresar la especialidad o servicio al que se remite al paciente" },
    { column: 120, field: "FECHA DE REMISION", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 121, field: "COMPLICACIONES", rule: "Se debe ingresar las complicaciones presentadas" },
    { column: 122, field: "NOVEDADES", rule: "Se debe ingresar las novedades" },
    { column: 123, field: "CAUSA DE MUERTE", rule: "Se debe ingresar la causa Basica de la muerte" },
    { column: 124, field: "FECHA DE MUERTE", rule: "Se debe Ingresar la Fecha de la siguiente forma: Año/Mes/ Día" },
    { column: 125, field: "OBSERVACIONES", rule: "Campo establecido para ingresar las observaciones que considere pertinente" }
];


export function RcvValidationRules() {
  return (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead className="w-[80px]">Columna</TableHead>
          <TableHead>Campo</TableHead>
          <TableHead>Regla de Validación</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        {validationRules.map((rule) => (
          <TableRow key={rule.column}>
            <TableCell className="font-medium text-center">{rule.column}</TableCell>
            <TableCell>{rule.field}</TableCell>
            <TableCell>{rule.rule}</TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  );
}
